### ISSUE TITLE
Additional Artists Variables - aditional artists

### ISSUE THREAD

**Issue by dfduarte78** [rdswift/picard-plugins#4]
Is it possible to limit the number of additional artists in an album?

Here is an example from the South Park album: https://musicbrainz.org/release/ba2581b2-233e-402b-83b1-3a8c928865bb
Track 1 has 6 artists:
Stan Marsh, Kenny McCormick, Kyle Broflovski, Eric Cartman, Sharon Marsh & Sheila Broflovski

I'd like to write to my file only, like, 3 artists max, primary and 2 additional..
ty

PS: my temporary solution:
$if($gt($len(%artist%),60),$left(%artist%,60),%artist%)

**Comment by rdswift** [comment]
I suggest using the `$slice()` function in your script to reduce the number of elements in the appropriate artists tag/variable.

**Comment by dfduarte78** [comment]
Woa, how did i miss this function? Thank you!
This selects the first 3 artists into _3artists: $setmulti(_3artists,$slice(%artists%,,3))
