### ISSUE TITLE
Additional Artist Variables no option menu

### ISSUE THREAD

**Issue by korongmambu** [rdswift/picard-plugins#9]
After install I can't access Additional Artist Variables menu because no option under plugins even after restart picard, neither work with script in README.md (country value always xx)

![image](https://github.com/user-attachments/assets/d30cae03-3e15-49cc-a4e7-22214436dd43)

**Comment by rdswift** [comment]
That's because there is no menu for "Additional Artists Variables".  If you're looking at the country information, then I think you should actually be using the "Additional Artists Details" plugin.

**Comment by korongmambu** [comment]
Oops! It has similar name, and what I need details instead of variables. Sorry, my bad
